### ISSUE TITLE
reform_date makes me want to die

### ISSUE THREAD

**Issue by johnwilsonICON** [johnwilsonICON/txvis#14]
Hi Simon,

I've tried (with great mental struggle) to create the reform_date function, but to no avail.  What I'd _like_ for it to do is something similar to reform_seq, but the treatments are repeated for as long as they are run. For example, assume patient with id AAA111 takes treatment 1 for 9 months, has a 3 month break, and then goes on treatment 2 for a year, I'd like the output of reform_date to look like this for that patient (using the default 3 month stepsize):

   pt_id         step_1   step_2   step_3   step_4    step_5   step_6   step_7   step_8    step_9   step_10  
1 AAK912    Tx1        Tx1       Tx1        None      Tx2        Tx2        Tx2        Tx2         <NA>     <NA> 

Right now I can use the findInterval funtion to get Tx1 into step_1 and Tx2 into step_5, but I'm really struggling with getting the treatments to show up for the duration of the time.

Could you give me some guidance with how you would approach this?

Thanks in advance!!

**Comment by SimonGoring** [comment]
@johnwilsonICON just curious, if there are two treatments overlapping, do you need rules?  Like:

`overlap` with options `last`, `first` and `majority`?

**Comment by johnwilsonICON** [comment]
I’ve never worked with overlap, but I was thinking the spoils would go to the majority. So if a patient has switches from treatment A to B at month 2 of a 3 month span then that timestep is counted as A.

I think that’d be the easiest starting point, but am happy to hear your thoughts if you have different ideas!

B

**Comment by SimonGoring** [comment]
I meant that `overlap` would be an option in the function we wrote.  I'll finish coding this up and then you can take a look at it.

**Comment by johnwilsonICON** [comment]
Thanks good sir ☺

**Comment by SimonGoring** [comment]
This seems to be resolved (we hope!) in pull request #15, but it's still slow and we should take another look at it.  Closing the issue for now.
