### ISSUE TITLE
Build `summary` function or add infrastructure.

### ISSUE THREAD

**Issue by SimonGoring** [johnwilsonICON/txvis#18]
What are the key components of a `summary` for the object?

**Comment by ellenkorol** [comment]
For treats:
Mean treatments per patient, overall and per treatment level
Number of treatments prescribed by class
Mean duration of treatment, overall and per treatment level
Min/max duration of treatment, overall and per treatment level

For events:
Mean events per patient, overall and per level
Mean duration of event, overall and per level
Min/max duration of event, overall and per level
