### ISSUE TITLE
txVis -> TxVis

### ISSUE THREAD

**Issue by ellenkorol** [johnwilsonICON/txvis#19]
@johnwilsonICON @SimonGoring @sgoring 

I'm noticing inconsistency regarding how this is labelled. While I personally find txVis more visually appealing, Ben countered that all the short forms of that sort have a capitalized first letter (i.e. Rx, Px, etc), so I deferred. 

I'll go through and start changing for create_txVis (now create_TxVis), print and summary, but as people come across this can they also make the change in the code?

**Comment by ellenkorol** [comment]
OK! now i'm getting an error when i try to build. I"m going to change everything back to txVis until this gets sorted.

==> Rcmd.exe INSTALL --no-multiarch --with-keep.source TxVis
- installing to library 'C:/Users/korole/Documents/R/win-library/3.2'
- installing _source_ package 'TxVis' ...
  *\* R
  *\* data
  **\* moving datasets to lazyload DB
  *\* inst
  *\* preparing package for lazy loading
  *\* help
  **\* installing help indices
  *\* building package indices
  *\* installing vignettes
  *\* testing if installed package can be loaded
  Warning: S3 methods 'print.txVis', 'summary.txVis' were declared in NAMESPACE but not found
  Error in namespaceExport(ns, exports) : undefined exports: create_txVis
  Error: loading failed
  Execution halted
  ERROR: loading failed
- removing 'C:/Users/korole/Documents/R/win-library/3.2/TxVis'
- restoring previous 'C:/Users/korole/Documents/R/win-library/3.2/TxVis'

Exited with status 1.

WARNING: Rtools is required to build R packages but is not currently

**Comment by SimonGoring** [comment]
@ellenkorol are you still getting this error?  I had no problems right up through my most recent push.

Can you & @johnwilsonICON and @sgoring all make sure that you pull before you make more changes?

Thanks!

**Comment by ellenkorol** [comment]
@SimonGoring I undid all my changes so that i could continue working on the summary, as i couldn't build with the error. I can try again though

**Comment by SimonGoring** [comment]
Okay.  I just want to check in on this issue (not the error).  Are we going to move back to using `TxVis` on everything?  So that the functions become: `Tx_indiv`, &cetera?  I'd rather just rename the package to txVis :)  @sgoring @johnwilsonICON

**Comment by SimonGoring** [comment]
FYI - to rename the repository (& package) is relatively straightforward:
1. @johnwilsonICON needs to go to the Admin page for the repo & rename it there.
2. Everyone else needs to delete their local copy & re-clone through RStudio (or `git` directly)

Then we have a package called `txVis` instead of `TxVis`.

**Comment by johnwilsonICON** [comment]
Alright, I've done step one of the rename process (renamed the repository here on github). Now everyone needs to do step two (delete your local copy and re-set up the project in RStudio). I'll check that you do this, Ellen and Sarah!!! (I know you'll do it, Simon)

**Comment by sgoring** [comment]
Exceeded your expectations. I did it myself. :-)

**Comment by ellenkorol** [comment]
@johnwilsonICON got the local copy deleted and reset. I should be good to go.

I've gone in and completed the summary function, but again tried to change all the "TxVis" or "txVis" in my code to "txvis" for consistency. After committing and re-pulling, I'm still getting this error when i try to build and I'm not sure why. 

==> Rcmd.exe INSTALL --no-multiarch --with-keep.source txvis
- installing to library 'C:/Users/korole/Documents/R/win-library/3.2'
- installing _source_ package 'TxVis' ...
  *\* R
  *\* data
  **\* moving datasets to lazyload DB
  *\* inst
  *\* preparing package for lazy loading
  *\* help
  **\* installing help indices
  *\* building package indices
  *\* installing vignettes
  *\* testing if installed package can be loaded
  Warning: S3 methods 'print.txVis', 'summary.txVis' were declared in NAMESPACE but not found
  Error in namespaceExport(ns, exports) : undefined exports: create_txVis
  Error: loading failed
  Execution halted
  ERROR: loading failed
- removing 'C:/Users/korole/Documents/R/win-library/3.2/TxVis'
- restoring previous 'C:/Users/korole/Documents/R/win-library/3.2/TxVis'

Exited with status 1.

**Comment by sgoring** [comment]
Can you change the name of the files? The file names are still with capitals but the function names are with lower case - I think that could be the problem. I also can't build anymore.

**Comment by johnwilsonICON** [comment]
Changed the file names and that hasn't fixed it. I think we need SIMON GORINGS help on this.

@SimonGoring any assistance you can provide?

**Comment by SimonGoring** [comment]
I think this is all fixed with Merge Request #30  and the commits there. It has to do mostly with the `DESCRIPTION` file and the `NAMESPACE` file.  It's a symptom of the fact that Windows machines don't recognize case changes in path names.  I think.  Regardless, I tracked down some problems & fixed them.
