### ISSUE TITLE
`events` is improperly encoded.

### ISSUE THREAD

**Issue by SimonGoring** [johnwilsonICON/txvis#20]
There's an issue, that the current `events` file has a `start` attribute that is of class `date`, but the `end` attribute is only an integer.  I'm not sure when that happened, but we need to fix it.  I looked at the version of `events.csv` that @johnwilsonICON deleted in commit https://github.com/johnwilsonICON/TxVis/commit/942bd547146b2dbd2f41b19efb4fd8577386a5d1 but it looks different than the `events.rda`, so I'm not sure what to restore.

@ellenkorol or @johnwilsonICON can you add `events` back in so that both columns are text strings?  We should also do this for the `treats` since as class `date` the `print` method basically returns an uninteresting integer.  It would be better for them all to look like "December 10, 2015" or something.

**Comment by ellenkorol** [comment]
@johnwilsonICON let me know if you want me to generate a new 'events' to match the new 'treats'

**Comment by SimonGoring** [comment]
@johnwilsonICON @ellenkorol I am now expecting that `treat` looks like this:

```
treat:
'data.frame':
 $ pat_id   : chr
 $ treatment: chr
 $ class    : chr
 $ sequence : num
 $ start    :chr 
 $ end      :chr
```

and that `events` looks like this:

```
event:
'data.frame':
 $ pat_id: chr
 $ event : chr
 $ start :chr
 $ end   : chr
```

where `chr` is a character string.

**Comment by johnwilsonICON** [comment]
Ok.

Just to clarify, Simon, you’d like the dates to be characters and written out in a format like “January 1, 2010”, or “1 January, 2010” or some such thing, right? (And then you input the date format when creating the TxVis object)

I will set up a final (hopefully) treat/events with those characteristics

B

**Comment by SimonGoring** [comment]
Yes, I think so.  That was the reason we set the "format" string in the `create_txvis` initially, so that people could pass in dates with any sort of formatting and it would output properly.  As it is, it can accept dates, but we should showcase that you can have any prior formatting and things will work.

**Comment by johnwilsonICON** [comment]
Perfect – this is done and the new files have been added.
