### ISSUE TITLE
Error in loadNamespace(name) : there is no package called ‘lubridate’ 

### ISSUE THREAD

**Issue by sgoring** [johnwilsonICON/txvis#24]
I added @import to the top of reform_dates but still get this message unless I manually install it myself.

**Comment by SimonGoring** [comment]
Do you have the package `lubridate` installed? 

This ought to be a problem only in the build process, but should get resolved when people actually install the package from github/CRAN.

**Comment by sgoring** [comment]
oh, maybe it was in the build then. will have to see.

**Comment by SimonGoring** [comment]
Can you confirm @sgoring ?  I'm closing this for now.
