### ISSUE TITLE
ggplot in tx_indiv

### ISSUE THREAD

**Issue by sgoring** [johnwilsonICON/txvis#25]
if you don't load ggplot2 library, you get this message:

Error in layer(data = data, mapping = mapping, stat = stat, geom = GeomTile,  : 
  could not find function "aes"

**Comment by SimonGoring** [comment]
I've made some changes to the package and am going through the existing issues.  This issue is not currently affecting me on a clean restart of the package.  That said, loading `txvis` should automatically load `ggplot2`, so this shouldn't be an error anymore.
