### ISSUE TITLE
d3alluvial

### ISSUE THREAD

**Issue by sgoring** [johnwilsonICON/txvis#27]
Totally doesn't seem to work. I think the reason the plot looks wonky is that for some reason the 'treatments' are actually the patient IDs. 
I can try to look at this tomorrow, or @SimonGoring might be able to look sooner, as it was modified from his original code (incorrectly...).

**Comment by SimonGoring** [comment]
Problem solved.  Issue closed.

**Comment by sgoring** [comment]
Node-specific colouring not working. It was working when it was first developed so just something went funny here; currently, all nodes are coloured the same.

**Comment by sgoring** [comment]
for @SimonGoring

**Comment by SimonGoring** [comment]
What coloring do we want?  The nodes colored or the links?

**Comment by sgoring** [comment]
In your original code, the nodes were multicoloured, and it was based on default colouring - you didn't have to use the colourScale or NodeGroup parameters. From what I've seen, I don't know if the links can be coloured, though it would be cool if they could. Nodes for now. And we're happy to tweak the colour scheme. I learned this morning a bit about colours in d3.

**Comment by SimonGoring** [comment]
We need to add some grouping factors.  We could use optional fields, with a default to the "From" sequence.  Is that okay?  @johnwilsonICON @ellenkorol

**Comment by sgoring** [comment]
I am working on another project and would love to use d3alluvial. Okay to add the default as you suggested. Note that d3 seems to break both due to colours but also if you don't have a sequence of 4.

**Comment by SimonGoring** [comment]
The issue was that the `NodeGroup` and `LinkGroup` categories cannot accept spaces in the factor levels.  By replacing the treatment names to remove spaces, using `gsub`, we can now get color.  This was an frustratingly hard problem to debug :)

Problem fixed in commit https://github.com/johnwilsonICON/txvis/commit/fb9334dfcc3d6abd401b2b86b3588b0c1f6bad5e.
