### ISSUE TITLE
Ugly For Loop in tx_indiv

### ISSUE THREAD

**Issue by sgoring** [johnwilsonICON/txvis#5]
This needs to be replaced with an apply statement and I need an assist so I don't waste time trying to figure it out all-by-myself:

  for (i in 2:nrow(treats_ind)) {
    if(treats_ind[i,"pt_id"] == treats_ind[i-1,"pt_id"]) treats_ind[i,"days"]<-treats_ind[i-1,"days"] + 1
  }

Rows 44:46 in tx_indivplot.r

It should return a sequential counter for days that resets for each new pt_id (the data set is sorted).

**Comment by SimonGoring** [comment]
This is fixed in commit 479eda8fa6bd98a367dcab745e72763925945406. The `for` loop is now a big `do.call` and `lapply` mess, but I think it's a bit cleaner and easier to parse.  I can comment it better if needed.
